from Bitstream import BitStream

#bt = BitStream("text.txt", "rb")

bt1 = BitStream("text1.txt", "wb",init_message = "Ola\n")

bt1.writeBit(int(1))
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(0)
bt1.writeBit(0)
bt1.writeBit(0)
bt1.writeBit(0)
bt1.writeBit(0)
bt1.writeBit(0)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)
bt1.writeBit(1)

bt1.endWrite()

bt = BitStream("text1.txt", "rb", read_FirstLine=True)
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print(bt.readBit())
print("first byte")
print(bt.readBit())
print(bt.first_line)

